on:
  push:
  pull_request:
    branches:
      - main
      - master

name: shinyapps-deploy

jobs:
  shinyapps-deploy:
    runs-on: ubuntu-18.04

    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SHINYAPPS_IO_TOKEN: ${{ secrets.SHINYAPPS_IO_TOKEN }}
      SHINYAPPS_IO_SECRET: ${{ secrets.SHINYAPPS_IO_SECRET }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - name: Install R dependecies
        run: |
          source("deploy-shinyapps-io.R")
        shell: Rscript {0}
